/**
 * Audit Scanner Page
 * 
 * Provides download link for CIS-Audit-Scanner.exe and upload interface
 * for audit reports generated by the standalone scanner.
 */

import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Paper, Button, Grid, Card, CardContent,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow,
  IconButton, Chip, LinearProgress, Dialog, DialogTitle, DialogContent,
  DialogActions, Alert, Snackbar, CircularProgress, Divider, List,
  ListItem, ListItemIcon, ListItemText, Link
} from '@mui/material';
import {
  CloudDownload as DownloadIcon,
  CloudUpload as UploadIcon,
  Assessment as ReportIcon,
  Delete as DeleteIcon,
  Visibility as ViewIcon,
  CheckCircle as CheckIcon,
  Warning as WarningIcon,
  Error as ErrorIcon,
  Info as InfoIcon,
  GetApp as GetAppIcon
} from '@mui/icons-material';
import axios from 'axios';

const API_BASE_URL = 'http://localhost:8000';

// REPLACE THIS WITH YOUR ACTUAL CLOUD STORAGE LINK
const AUDIT_SCANNER_DOWNLOAD_URL = 'https://drive.google.com/uc?export=download&id=YOUR_FILE_ID';

const AuditScanner = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [selectedReport, setSelectedReport] = useState(null);
  const [detailsDialog, setDetailsDialog] = useState(false);
  const [snackbar, setSnackbar] = useState({
    open: false,
    message: '',
    severity: 'success'
  });

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const response = await axios.get(`${API_BASE_URL}/audit/reports`);
      setReports(response.data.reports || []);
    } catch (error) {
      console.error('Error fetching audit reports:', error);
      showSnackbar('Error loading audit reports', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleFileUpload = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    // Validate file type
    if (!file.name.endsWith('.pdf')) {
      showSnackbar('Please upload a PDF file generated by CIS-Audit-Scanner.exe', 'error');
      return;
    }

    const formData = new FormData();
    formData.append('file', file);

    try {
      setUploading(true);
      setUploadProgress(0);

      const response = await axios.post(
        `${API_BASE_URL}/audit/upload-report`,
        formData,
        {
          headers: { 'Content-Type': 'multipart/form-data' },
          onUploadProgress: (progressEvent) => {
            const percentCompleted = Math.round((progressEvent.loaded * 100) / progressEvent.total);
            setUploadProgress(percentCompleted);
          }
        }
      );

      showSnackbar(
        `Report uploaded! Compliance Score: ${response.data.compliance_score}%`,
        response.data.compliance_score >= 80 ? 'success' : 'warning'
      );
      
      fetchReports(); // Refresh list
      
      // Clear file input
      event.target.value = '';
    } catch (error) {
      console.error('Upload error:', error);
      showSnackbar(
        `Upload failed: ${error.response?.data?.detail || error.message}`,
        'error'
      );
    } finally {
      setUploading(false);
      setUploadProgress(0);
    }
  };

  const handleViewDetails = async (report) => {
    try {
      const response = await axios.get(`${API_BASE_URL}/audit/report/${report.report_id}`);
      setSelectedReport(response.data.report);
      setDetailsDialog(true);
    } catch (error) {
      console.error('Error fetching report details:', error);
      showSnackbar('Error loading report details', 'error');
    }
  };

  const handleDownloadReport = (reportId) => {
    window.open(`${API_BASE_URL}/audit/download/${reportId}`, '_blank');
  };

  const handleDeleteReport = async (reportId) => {
    if (!window.confirm('Are you sure you want to delete this audit report?')) {
      return;
    }

    try {
      await axios.delete(`${API_BASE_URL}/audit/report/${reportId}`);
      showSnackbar('Report deleted successfully', 'success');
      fetchReports();
    } catch (error) {
      console.error('Error deleting report:', error);
      showSnackbar('Error deleting report', 'error');
    }
  };

  const showSnackbar = (message, severity = 'success') => {
    setSnackbar({ open: true, message, severity });
  };

  const handleCloseSnackbar = () => {
    setSnackbar({ ...snackbar, open: false });
  };

  const getComplianceColor = (score) => {
    if (score >= 90) return 'success';
    if (score >= 80) return 'info';
    if (score >= 70) return 'warning';
    return 'error';
  };

  const getComplianceIcon = (score) => {
    if (score >= 90) return <CheckIcon />;
    if (score >= 70) return <WarningIcon />;
    return <ErrorIcon />;
  };

  return (
    <Box sx={{ p: 3 }}>
      {/* Header */}
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" gutterBottom>
          CIS Audit Scanner
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Download the standalone audit scanner to check your Windows 10/11 system compliance with CIS benchmarks.
          Then upload the generated report here for detailed analysis.
        </Typography>
      </Box>

      {/* How It Works Section */}
      <Card sx={{ mb: 3, bgcolor: '#f5f5f5' }}>
        <CardContent>
          <Typography variant="h6" gutterBottom sx={{ display: 'flex', alignItems: 'center' }}>
            <InfoIcon sx={{ mr: 1 }} color="primary" />
            How It Works
          </Typography>
          <List dense>
            <ListItem>
              <ListItemIcon>
                <Typography color="primary" fontWeight="bold">1</Typography>
              </ListItemIcon>
              <ListItemText 
                primary="Download CIS-Audit-Scanner.exe"
                secondary="Click the download button below to get the standalone scanner"
              />
            </ListItem>
            <ListItem>
              <ListItemIcon>
                <Typography color="primary" fontWeight="bold">2</Typography>
              </ListItemIcon>
              <ListItemText 
                primary="Run as Administrator on your Windows system"
                secondary="Right-click the .exe file and select 'Run as administrator'"
              />
            </ListItem>
            <ListItem>
              <ListItemIcon>
                <Typography color="primary" fontWeight="bold">3</Typography>
              </ListItemIcon>
              <ListItemText 
                primary="Wait for scan to complete (2-5 minutes)"
                secondary="Scanner will check 100+ CIS policies and generate a PDF report"
              />
            </ListItem>
            <ListItem>
              <ListItemIcon>
                <Typography color="primary" fontWeight="bold">4</Typography>
              </ListItemIcon>
              <ListItemText 
                primary="Upload the PDF report here"
                secondary="Get detailed analysis, visualizations, and remediation recommendations"
              />
            </ListItem>
          </List>
        </CardContent>
      </Card>

      {/* Action Buttons */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
        {/* Download Scanner */}
        <Grid item xs={12} md={6}>
          <Card sx={{ height: '100%', bgcolor: '#e3f2fd' }}>
            <CardContent sx={{ textAlign: 'center', py: 4 }}>
              <DownloadIcon sx={{ fontSize: 60, color: 'primary.main', mb: 2 }} />
              <Typography variant="h6" gutterBottom>
                Download Audit Scanner
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Standalone Windows executable (15-20 MB)
                <br />
                Works offline • No installation required
              </Typography>
              <Button
                variant="contained"
                size="large"
                startIcon={<GetAppIcon />}
                onClick={() => window.open(AUDIT_SCANNER_DOWNLOAD_URL, '_blank')}
                sx={{ mb: 1 }}
              >
                Download CIS-Audit-Scanner.exe
              </Button>
              <Typography variant="caption" display="block" color="text.secondary" sx={{ mt: 1 }}>
                Windows 10/11 • 64-bit • Requires Administrator
              </Typography>
            </CardContent>
          </Card>
        </Grid>

        {/* Upload Report */}
        <Grid item xs={12} md={6}>
          <Card sx={{ height: '100%', bgcolor: '#f3e5f5' }}>
            <CardContent sx={{ textAlign: 'center', py: 4 }}>
              <UploadIcon sx={{ fontSize: 60, color: 'secondary.main', mb: 2 }} />
              <Typography variant="h6" gutterBottom>
                Upload Audit Report
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Upload the PDF report generated by the scanner
                <br />
                Get detailed analysis and recommendations
              </Typography>
              <Button
                variant="contained"
                color="secondary"
                size="large"
                component="label"
                startIcon={uploading ? <CircularProgress size={20} color="inherit" /> : <UploadIcon />}
                disabled={uploading}
              >
                {uploading ? 'Uploading...' : 'Upload PDF Report'}
                <input
                  type="file"
                  hidden
                  accept=".pdf"
                  onChange={handleFileUpload}
                />
              </Button>
              {uploading && (
                <Box sx={{ mt: 2, width: '100%' }}>
                  <LinearProgress variant="determinate" value={uploadProgress} />
                  <Typography variant="caption" color="text.secondary">
                    {uploadProgress}% uploaded
                  </Typography>
                </Box>
              )}
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* System Requirements */}
      <Alert severity="info" sx={{ mb: 3 }}>
        <Typography variant="subtitle2" gutterBottom>
          <strong>System Requirements for Scanner:</strong>
        </Typography>
        <Typography variant="body2">
          • Windows 10 or Windows 11 (64-bit)
          <br />
          • Administrator privileges
          <br />
          • No internet connection required (works on airgapped systems)
          <br />
          • Safe: Read-only scanner, makes no system changes
        </Typography>
      </Alert>

      <Divider sx={{ my: 4 }} />

      {/* Reports List */}
      <Box sx={{ mb: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="h5">
          Uploaded Audit Reports ({reports.length})
        </Typography>
        <Button
          variant="outlined"
          startIcon={loading ? <CircularProgress size={20} /> : <ReportIcon />}
          onClick={fetchReports}
          disabled={loading}
        >
          Refresh
        </Button>
      </Box>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}>
          <CircularProgress />
        </Box>
      ) : reports.length === 0 ? (
        <Paper sx={{ p: 4, textAlign: 'center' }}>
          <ReportIcon sx={{ fontSize: 60, color: 'text.secondary', mb: 2 }} />
          <Typography variant="h6" color="text.secondary">
            No audit reports uploaded yet
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Download the scanner, run it on your system, and upload the report here.
          </Typography>
        </Paper>
      ) : (
        <TableContainer component={Paper}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell><strong>Computer Name</strong></TableCell>
                <TableCell><strong>Scan Date</strong></TableCell>
                <TableCell><strong>Compliance Score</strong></TableCell>
                <TableCell><strong>Uploaded</strong></TableCell>
                <TableCell><strong>Size</strong></TableCell>
                <TableCell><strong>Actions</strong></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {reports.map((report) => (
                <TableRow key={report.report_id}>
                  <TableCell>{report.computer_name || 'Unknown'}</TableCell>
                  <TableCell>
                    {report.scan_date ? new Date(report.scan_date).toLocaleString() : 'Unknown'}
                  </TableCell>
                  <TableCell>
                    <Chip
                      icon={getComplianceIcon(report.compliance_score)}
                      label={`${report.compliance_score}%`}
                      color={getComplianceColor(report.compliance_score)}
                      size="small"
                    />
                  </TableCell>
                  <TableCell>
                    {new Date(report.uploaded_at).toLocaleString()}
                  </TableCell>
                  <TableCell>
                    {(report.file_size / (1024 * 1024)).toFixed(2)} MB
                  </TableCell>
                  <TableCell>
                    <IconButton
                      size="small"
                      color="primary"
                      onClick={() => handleViewDetails(report)}
                      title="View Details"
                    >
                      <ViewIcon />
                    </IconButton>
                    <IconButton
                      size="small"
                      color="info"
                      onClick={() => handleDownloadReport(report.report_id)}
                      title="Download PDF"
                      disabled={!report.pdf_exists}
                    >
                      <GetAppIcon />
                    </IconButton>
                    <IconButton
                      size="small"
                      color="error"
                      onClick={() => handleDeleteReport(report.report_id)}
                      title="Delete Report"
                    >
                      <DeleteIcon />
                    </IconButton>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      )}

      {/* Report Details Dialog */}
      <Dialog
        open={detailsDialog}
        onClose={() => setDetailsDialog(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          Audit Report Details
        </DialogTitle>
        <DialogContent>
          {selectedReport && (
            <Box>
              <Grid container spacing={2} sx={{ mb: 3 }}>
                <Grid item xs={12} md={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Computer Name
                  </Typography>
                  <Typography variant="body1">
                    {selectedReport.computer_name || 'Unknown'}
                  </Typography>
                </Grid>
                <Grid item xs={12} md={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Scan Date
                  </Typography>
                  <Typography variant="body1">
                    {selectedReport.scan_date ? new Date(selectedReport.scan_date).toLocaleString() : 'Unknown'}
                  </Typography>
                </Grid>
                <Grid item xs={12} md={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Compliance Score
                  </Typography>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <Typography variant="h4" color={getComplianceColor(selectedReport.compliance_score) + '.main'}>
                      {selectedReport.compliance_score}%
                    </Typography>
                    <Chip
                      label={selectedReport.status || 'Unknown'}
                      color={getComplianceColor(selectedReport.compliance_score)}
                      size="small"
                    />
                  </Box>
                </Grid>
                <Grid item xs={12} md={6}>
                  <Typography variant="subtitle2" color="text.secondary">
                    Grade
                  </Typography>
                  <Typography variant="h4">
                    {selectedReport.grade || 'N/A'}
                  </Typography>
                </Grid>
              </Grid>

              <Divider sx={{ my: 2 }} />

              <Typography variant="subtitle2" color="text.secondary" gutterBottom>
                Report Information
              </Typography>
              <Typography variant="body2" sx={{ mb: 1 }}>
                <strong>Uploaded:</strong> {new Date(selectedReport.uploaded_at).toLocaleString()}
              </Typography>
              <Typography variant="body2" sx={{ mb: 1 }}>
                <strong>File Size:</strong> {(selectedReport.file_size / (1024 * 1024)).toFixed(2)} MB
              </Typography>
              <Typography variant="body2" sx={{ mb: 1 }}>
                <strong>Original Filename:</strong> {selectedReport.original_filename || 'Unknown'}
              </Typography>
              <Typography variant="body2">
                <strong>Report ID:</strong> {selectedReport.report_id}
              </Typography>

              {selectedReport.download_url && (
                <Box sx={{ mt: 3 }}>
                  <Button
                    variant="contained"
                    startIcon={<GetAppIcon />}
                    onClick={() => handleDownloadReport(selectedReport.report_id)}
                    fullWidth
                  >
                    Download PDF Report
                  </Button>
                </Box>
              )}
            </Box>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDetailsDialog(false)}>Close</Button>
        </DialogActions>
      </Dialog>

      {/* Snackbar for notifications */}
      <Snackbar
        open={snackbar.open}
        autoHideDuration={6000}
        onClose={handleCloseSnackbar}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert onClose={handleCloseSnackbar} severity={snackbar.severity} sx={{ width: '100%' }}>
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default AuditScanner;
